name: Python

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Python

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6

      - name: Build
        run: uv sync --all-extras --dev

      - name: mypy
        run: make mypy

      - name: Test
        run: make test
